### ISSUE TITLE
Record is too large. Payload size too big. Skipping...

### ISSUE THREAD

**Issue by nikhilbhalwankar** [algolia/firestore-algolia-search#154]
I have around 2800 documents from cloud firestore collection to be imported into algolia for indexing. However only 2200 are getting imported. For remaining below error is thrown

`{"severity":"WARNING","message":"[\n  'Payload size too big, skipping ...',\n  Error: Record is too large.\n      at extract (/home/nikhil/.npm/_npx/0ca4ecfa9810ae5b/node_modules/firestore-algolia-search/lib/extract.js:60:15)\n      at runMicrotasks (<anonymous>)\n      at processTicksAndRejections (internal/process/task_queues.js:95:5)\n      at async processQuery (/home/nikhil/.npm/_npx/0ca4ecfa9810ae5b/node_modules/firestore-algolia-search/lib/import/index.js:53:29)\n      at async retrieveDataFromFirestore (/home/nikhil/.npm/_npx/0ca4ecfa9810ae5b/node_modules/firestore-algolia-search/lib/import/index.js:79:9)\n]"}`

How to find which document has large record? I am using below command to import data

`npx firestore-algolia-search`

**Comment by amit20897** [comment]
To find which are not getting imported, you can check algolia directly.

use this link (update your app id):
https://dashboard.algolia.com/apps/<APP_ID>/explorer/logs

or go to:
Your index -> Click the "Search API Logs" tab -> search for 400 error -> check the request data tab
