### ISSUE TITLE
ext-firestore-algolia-search-executeFullIndexOperation Error

### ISSUE THREAD

**Issue by guskuma** [algolia/firestore-algolia-search#174]
I'm trying to index all fields of my collection, but I have the following error when executing full index on existing collection:
'''
{"name":"ApiError","message":"Error: Unhandled error\n    at entryFromArgs (/workspace/node_modules/firebase-functions/lib/logger/index.js:130:19)\n    at Object.error (/workspace/node_modules/firebase-functions/lib/logger/index.js:116:11)\n    at /workspace/node_modules/firebase-functions/lib/common/providers/tasks.js:70:24\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","status":400,"transporterStackTrace":[{"request":{"data":"{\"requests\":[{\"action\":\"addObject\",\"body\":{\"pinned\":false,\"nameSearch\":\"tiaguin\",\"phones\":[\"+55 35 9999-6351\"],\"originalName\":\"Tiaguin\",\"archived\":false,\"uid\":\"01IawVN9KPhyGWCQQwUMSz0AxB73\",\"referrers\":[\"\"],\"imageUrl\":\"\",\"lastReferrer\":\"\",\"name\":\"Tiaguin\",\"group\":\"ecf988d0-eacd-4c4d-a4db-401d008d80b5\",\"lastReferenceDate\":1660750648370,\"statusChangedAt\":1660750648370,\"lastUpdate\":1660750648370,\"creationDate\":1660750648370,\"validated\":0,\"objections\":[],\"status\":\"SEM_CONTATO\",\"tags\":[],\"interest\":99,\"geoCountryCode\":\"55\",\"geoOffsetInMinutes\":-180,\"geoLocation\":\"Minas Gerais, BR\",\"geoTimezone\":[\"America/Sao_Paulo\"],\"geoCountry\":\"BR\",\"geoOffset\":-3,\"objectID\":\"032419bb2fab2e079ea5df038a6238b0a992ae1f122b6d90c8639f8ad0dd0cd2\",\"path\":\"customers/01IawVN9KPhyGWCQQwUMSz0AxB73/referreds/032419bb2fab2e079ea5df038a6238b0a992ae1f122b6d90c8639f8ad0dd0cd2\",\"lastmodified\":{\"_operation\":\"IncrementSet\",\"value\":1687283449339}}}...
'''

This is my config:
![image](https://github.com/algolia/firestore-algolia-search/assets/25397039/b5a38401-9b38-42bc-96ab-5ba74a19ac9b)

- I don't know if this is relevant but I have installed and uninstalled this extension before. 
- I double-checked and my api key can write to my index.
- Some objects may have the same id within different subcollections

**Comment by guskuma** [comment]
After a while it just started working. Don't know why!
