### ISSUE TITLE
Update to 1.2.2 (from 1.2.0): Firebase Extension doesn't sync Algolia index anymore

### ISSUE THREAD

**Issue by doc-ramadani** [algolia/firestore-algolia-search#203]
Hello contributors,

I started to integrate Algolia into my app 2 weeks ago. Everything worked fine. The detailed documentation was very helpful to implement Algolia into my infrastructure. Today I updated the Firebase Extension from version 1.2.0 to 1.2.2 while adding another instance of the extension for a new Firestore collection.

After updating the extension from version 1.2.0 to 1.2.2 the cloud function doesn't sync the Algolia index anymore. No matter if I add a document to a collection or if I update an existing document from my collection. I checked the GC log files for the function:

---

ext-firestore-algolia-search-arrangers-executeIndexOperation

Error: Error when performing Algolia index
    at entryFromArgs (/workspace/node_modules/firebase-functions/lib/logger/index.js:130:19)
    at Object.error (/workspace/node_modules/firebase-functions/lib/logger/index.js:116:11)
    at Object.error (/workspace/lib/logs.js:38:33)
    at handleCreateDocument (/workspace/lib/index.js:60:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /workspace/lib/index.js:122:13

---

The server status that GCP receives from Algolia is:

---

name: "ApiError"
status: 400

---

Since I haven't changed anything else in my infrastructure, I can only assume that something has crept into the relevant branch.

Marco

**Comment by doc-ramadani** [comment]
Hello contributors,

after hours of testing I figured out that this error occurred only on my initial update. After un-installing and re-installing the Algolia Firebase Extension everything worked fine again.

Therefore I will close this issue. I hope I haven't caused any inconvenience. I think the error has to do with the way Google is currently integrating the extensions into the Firebase Console. This feature is still beta.

Marco
