### ISSUE TITLE
Reindexing fails when updating indexable fields

### ISSUE THREAD

**Issue by jakelaws1** [algolia/firestore-algolia-search#214]
Steps to reproduce:
1. setup the firebase extension with indexable fields
2. update the extension adding new indexable fields
    - I am not sure if the fields I am adding is making them item above 10kb and that's why it's failing? And then it can't recover when I remove it? Regardless I think the error messaging makes this impossible to tell.
    - The interesting thing here is some items do get updated with these new fields (hence my hypothesis above)
3. After receiving the below error I try to remove the above reconfigured indexable fields and it continues to fail.
4. This leaves the extension in a perpetual "Runtime Status: Processing" state

Error:
`{"name":"ApiError","message":"Error: Unhandled error\n    at entryFromArgs (/workspace/node_modules/firebase-functions/lib/logger/index.js:130:19)\n    at Object.error (/workspace/node_modules/firebase-functions/lib/logger/index.js:116:11)\n    at /workspace/node_modules/firebase-functions/lib/common/providers/tasks.js:91:24\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","status":429,"transporterStackTrace":`

The only other error I am seeing which may be relevant:
```
iam.googleapis.com

…e.iam.admin.v1.CreateServiceAccount

projects/roamerai-d8e29

service-409449841200@gcp-…
Service account ext-firestore-algolia-search already exists within project projects/roamerai-d8e29.

```

**Comment by smomin** [comment]
Are you seeing the requests coming to Algolia?  If so, can you share the logs from Algolia?
